name: oni-ai-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - cudatoolkit=11.8
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
      - websockets>=11.0
      - PySide6>=6.5.0
      - pyqtgraph>=0.13.0
      - stable-baselines3>=2.0.0
      - gymnasium>=0.28.0
      - tensorboard>=2.13.0
      - pyinstaller>=5.13.0
