name: oni-ai-env

channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.10
  - websockets=11.0.3
  - openai>=1.30.0
  - pyyaml=6.0.1
  - wandb=0.16.0
  - pytest=7.4.3
  - pytest-asyncio=0.21.1
  - python-dotenv=1.0.0
  - cachetools=5.3.2
  - numpy=1.24.3
  - orjson=3.10.7
  - pydantic=2.9.2
